
-- oracle to sqlite
-- 이식자 jaybon
-- https://velog.io/@jaybon
-- 참고 : 프로시저 및 뷰 제외함

-- creating tables:

CREATE TABLE REGIONS 
(
  REGION_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, REGION_NAME TEXT 
);

CREATE TABLE JOBS 
(
  JOB_ID TEXT PRIMARY KEY NOT NULL
, JOB_TITLE TEXT NOT NULL 
, MIN_SALARY INTEGER 
, MAX_SALARY INTEGER
);

CREATE TABLE COUNTRIES 
(
  COUNTRY_ID TEXT PRIMARY KEY NOT NULL
, COUNTRY_NAME TEXT 
, REGION_ID INTEGER
, FOREIGN KEY(REGION_ID) REFERENCES REGIONS(REGION_ID) ON DELETE CASCADE
 );

CREATE TABLE LOCATIONS 
(
  LOCATION_ID INTEGER PRIMARY KEY NOT NULL
, STREET_ADDRESS TEXT 
, POSTAL_CODE TEXT 
, CITY TEXT NOT NULL 
, STATE_PROVINCE TEXT 
, COUNTRY_ID TEXT 
, FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID) ON DELETE CASCADE
);

CREATE TABLE DEPARTMENTS 
(
  DEPARTMENT_ID INTEGER PRIMARY KEY NOT NULL
, DEPARTMENT_NAME TEXT NOT NULL 
, MANAGER_ID INTEGER
, LOCATION_ID INTEGER
, FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL
, FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE SET NULL
);

CREATE TABLE EMPLOYEES 
(
  EMPLOYEE_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, FIRST_NAME TEXT 
, LAST_NAME TEXT NOT NULL 
, EMAIL TEXT NOT NULL 
, PHONE_NUMBER TEXT 
, HIRE_DATE TEXT NOT NULL 
, JOB_ID TEXT NOT NULL 
, SALARY REAL
, COMMISSION_PCT REAL
, MANAGER_ID INTEGER
, DEPARTMENT_ID INTEGER
, FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
, FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
, FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE RESTRICT
);

CREATE TABLE JOB_HISTORY 
(
  EMPLOYEE_ID INTEGER NOT NULL
, START_DATE TEXT NOT NULL 
, END_DATE TEXT NOT NULL 
, JOB_ID TEXT NOT NULL 
, DEPARTMENT_ID INTEGER
, FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE
, FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
); 


-- creating indexes:

CREATE UNIQUE INDEX EMP_EMP_ID_PK ON EMPLOYEES (EMPLOYEE_ID ASC);
CREATE INDEX EMP_MANAGER_IX ON EMPLOYEES (MANAGER_ID ASC);
CREATE INDEX EMP_DEPARTMENT_IX ON EMPLOYEES (DEPARTMENT_ID ASC);
CREATE INDEX EMP_JOB_IX ON EMPLOYEES (JOB_ID ASC); 
CREATE INDEX EMP_NAME_IX ON EMPLOYEES (LAST_NAME ASC, FIRST_NAME ASC); 
CREATE UNIQUE INDEX EMP_EMAIL_UK ON EMPLOYEES (EMAIL ASC);

CREATE UNIQUE INDEX DEPT_ID_PK ON DEPARTMENTS (DEPARTMENT_ID ASC);
CREATE INDEX DEPT_LOCATION_IX ON DEPARTMENTS (LOCATION_ID ASC);

CREATE INDEX LOC_CITY_IX ON LOCATIONS (CITY ASC);
CREATE INDEX LOC_COUNTRY_IX ON LOCATIONS (COUNTRY_ID ASC);
CREATE INDEX LOC_STATE_PROVINCE_IX ON LOCATIONS (STATE_PROVINCE ASC);

CREATE UNIQUE INDEX REG_ID_PK ON REGIONS (REGION_ID ASC);

CREATE UNIQUE INDEX JOB_ID_PK ON JOBS (JOB_ID ASC); 
CREATE INDEX JHIST_EMPLOYEE_IX ON JOB_HISTORY (EMPLOYEE_ID ASC);
CREATE INDEX JHIST_DEPARTMENT_IX ON JOB_HISTORY (DEPARTMENT_ID ASC);
CREATE UNIQUE INDEX JHIST_EMP_ID_ST_DATE_PK ON JOB_HISTORY (EMPLOYEE_ID ASC, START_DATE ASC);
CREATE INDEX JHIST_JOB_IX ON JOB_HISTORY (JOB_ID ASC);


